# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objectDemos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='objectDemos.proto',
  package='grpcDemo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11objectDemos.proto\x12\x08grpcDemo\"\x1f\n\x0bUserRawData\x12\x10\n\x08userData\x18\x01 \x03(\t\"\x9d\x01\n\x12UserRawDataRequest\x12>\n\tusersAttr\x18\x01 \x03(\x0b\x32+.grpcDemo.UserRawDataRequest.UsersAttrEntry\x1aG\n\x0eUsersAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.grpcDemo.UserRawData:\x02\x38\x01\"3\n\x13UserRawDataResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0e\n\x06\x65rrMsg\x18\x02 \x01(\t2a\n\x0fUpdateUserModel\x12N\n\x0fUpdateUserModel\x12\x1c.grpcDemo.UserRawDataRequest\x1a\x1d.grpcDemo.UserRawDataResponseb\x06proto3')
)




_USERRAWDATA = _descriptor.Descriptor(
  name='UserRawData',
  full_name='grpcDemo.UserRawData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userData', full_name='grpcDemo.UserRawData.userData', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=62,
)


_USERRAWDATAREQUEST_USERSATTRENTRY = _descriptor.Descriptor(
  name='UsersAttrEntry',
  full_name='grpcDemo.UserRawDataRequest.UsersAttrEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpcDemo.UserRawDataRequest.UsersAttrEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='grpcDemo.UserRawDataRequest.UsersAttrEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=222,
)

_USERRAWDATAREQUEST = _descriptor.Descriptor(
  name='UserRawDataRequest',
  full_name='grpcDemo.UserRawDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='usersAttr', full_name='grpcDemo.UserRawDataRequest.usersAttr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_USERRAWDATAREQUEST_USERSATTRENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=222,
)


_USERRAWDATARESPONSE = _descriptor.Descriptor(
  name='UserRawDataResponse',
  full_name='grpcDemo.UserRawDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='grpcDemo.UserRawDataResponse.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errMsg', full_name='grpcDemo.UserRawDataResponse.errMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=275,
)

_USERRAWDATAREQUEST_USERSATTRENTRY.fields_by_name['value'].message_type = _USERRAWDATA
_USERRAWDATAREQUEST_USERSATTRENTRY.containing_type = _USERRAWDATAREQUEST
_USERRAWDATAREQUEST.fields_by_name['usersAttr'].message_type = _USERRAWDATAREQUEST_USERSATTRENTRY
DESCRIPTOR.message_types_by_name['UserRawData'] = _USERRAWDATA
DESCRIPTOR.message_types_by_name['UserRawDataRequest'] = _USERRAWDATAREQUEST
DESCRIPTOR.message_types_by_name['UserRawDataResponse'] = _USERRAWDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRawData = _reflection.GeneratedProtocolMessageType('UserRawData', (_message.Message,), {
  'DESCRIPTOR' : _USERRAWDATA,
  '__module__' : 'objectDemos_pb2'
  # @@protoc_insertion_point(class_scope:grpcDemo.UserRawData)
  })
_sym_db.RegisterMessage(UserRawData)

UserRawDataRequest = _reflection.GeneratedProtocolMessageType('UserRawDataRequest', (_message.Message,), {

  'UsersAttrEntry' : _reflection.GeneratedProtocolMessageType('UsersAttrEntry', (_message.Message,), {
    'DESCRIPTOR' : _USERRAWDATAREQUEST_USERSATTRENTRY,
    '__module__' : 'objectDemos_pb2'
    # @@protoc_insertion_point(class_scope:grpcDemo.UserRawDataRequest.UsersAttrEntry)
    })
  ,
  'DESCRIPTOR' : _USERRAWDATAREQUEST,
  '__module__' : 'objectDemos_pb2'
  # @@protoc_insertion_point(class_scope:grpcDemo.UserRawDataRequest)
  })
_sym_db.RegisterMessage(UserRawDataRequest)
_sym_db.RegisterMessage(UserRawDataRequest.UsersAttrEntry)

UserRawDataResponse = _reflection.GeneratedProtocolMessageType('UserRawDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERRAWDATARESPONSE,
  '__module__' : 'objectDemos_pb2'
  # @@protoc_insertion_point(class_scope:grpcDemo.UserRawDataResponse)
  })
_sym_db.RegisterMessage(UserRawDataResponse)


_USERRAWDATAREQUEST_USERSATTRENTRY._options = None

_UPDATEUSERMODEL = _descriptor.ServiceDescriptor(
  name='UpdateUserModel',
  full_name='grpcDemo.UpdateUserModel',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=277,
  serialized_end=374,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateUserModel',
    full_name='grpcDemo.UpdateUserModel.UpdateUserModel',
    index=0,
    containing_service=None,
    input_type=_USERRAWDATAREQUEST,
    output_type=_USERRAWDATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPDATEUSERMODEL)

DESCRIPTOR.services_by_name['UpdateUserModel'] = _UPDATEUSERMODEL

# @@protoc_insertion_point(module_scope)
