# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import objectDemos_pb2 as objectDemos__pb2


class UpdateUserModelStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UpdateUserModel = channel.unary_unary(
        '/grpcDemo.UpdateUserModel/UpdateUserModel',
        request_serializer=objectDemos__pb2.UserRawDataRequest.SerializeToString,
        response_deserializer=objectDemos__pb2.UserRawDataResponse.FromString,
        )


class UpdateUserModelServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def UpdateUserModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UpdateUserModelServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UpdateUserModel': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserModel,
          request_deserializer=objectDemos__pb2.UserRawDataRequest.FromString,
          response_serializer=objectDemos__pb2.UserRawDataResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpcDemo.UpdateUserModel', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
