# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapDemos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mapDemos.proto',
  package='grpcDemo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0emapDemos.proto\x12\x08grpcDemo\"k\n\tMapObject\x12/\n\x06mapObj\x18\x01 \x03(\x0b\x32\x1f.grpcDemo.MapObject.MapObjEntry\x1a-\n\x0bMapObjEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"y\n\nMapRequest\x12*\n\x03map\x18\x01 \x03(\x0b\x32\x1d.grpcDemo.MapRequest.MapEntry\x1a?\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.grpcDemo.MapObject:\x02\x38\x01\"\x1b\n\x0bMapResponse\x12\x0c\n\x04resp\x18\x01 \x01(\t2E\n\nGreeterMap\x12\x37\n\x08SayHello\x12\x14.grpcDemo.MapRequest\x1a\x15.grpcDemo.MapResponseb\x06proto3')
)




_MAPOBJECT_MAPOBJENTRY = _descriptor.Descriptor(
  name='MapObjEntry',
  full_name='grpcDemo.MapObject.MapObjEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpcDemo.MapObject.MapObjEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='grpcDemo.MapObject.MapObjEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=135,
)

_MAPOBJECT = _descriptor.Descriptor(
  name='MapObject',
  full_name='grpcDemo.MapObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mapObj', full_name='grpcDemo.MapObject.mapObj', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MAPOBJECT_MAPOBJENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=135,
)


_MAPREQUEST_MAPENTRY = _descriptor.Descriptor(
  name='MapEntry',
  full_name='grpcDemo.MapRequest.MapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpcDemo.MapRequest.MapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='grpcDemo.MapRequest.MapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=258,
)

_MAPREQUEST = _descriptor.Descriptor(
  name='MapRequest',
  full_name='grpcDemo.MapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='map', full_name='grpcDemo.MapRequest.map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MAPREQUEST_MAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=258,
)


_MAPRESPONSE = _descriptor.Descriptor(
  name='MapResponse',
  full_name='grpcDemo.MapResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resp', full_name='grpcDemo.MapResponse.resp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=287,
)

_MAPOBJECT_MAPOBJENTRY.containing_type = _MAPOBJECT
_MAPOBJECT.fields_by_name['mapObj'].message_type = _MAPOBJECT_MAPOBJENTRY
_MAPREQUEST_MAPENTRY.fields_by_name['value'].message_type = _MAPOBJECT
_MAPREQUEST_MAPENTRY.containing_type = _MAPREQUEST
_MAPREQUEST.fields_by_name['map'].message_type = _MAPREQUEST_MAPENTRY
DESCRIPTOR.message_types_by_name['MapObject'] = _MAPOBJECT
DESCRIPTOR.message_types_by_name['MapRequest'] = _MAPREQUEST
DESCRIPTOR.message_types_by_name['MapResponse'] = _MAPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapObject = _reflection.GeneratedProtocolMessageType('MapObject', (_message.Message,), {

  'MapObjEntry' : _reflection.GeneratedProtocolMessageType('MapObjEntry', (_message.Message,), {
    'DESCRIPTOR' : _MAPOBJECT_MAPOBJENTRY,
    '__module__' : 'mapDemos_pb2'
    # @@protoc_insertion_point(class_scope:grpcDemo.MapObject.MapObjEntry)
    })
  ,
  'DESCRIPTOR' : _MAPOBJECT,
  '__module__' : 'mapDemos_pb2'
  # @@protoc_insertion_point(class_scope:grpcDemo.MapObject)
  })
_sym_db.RegisterMessage(MapObject)
_sym_db.RegisterMessage(MapObject.MapObjEntry)

MapRequest = _reflection.GeneratedProtocolMessageType('MapRequest', (_message.Message,), {

  'MapEntry' : _reflection.GeneratedProtocolMessageType('MapEntry', (_message.Message,), {
    'DESCRIPTOR' : _MAPREQUEST_MAPENTRY,
    '__module__' : 'mapDemos_pb2'
    # @@protoc_insertion_point(class_scope:grpcDemo.MapRequest.MapEntry)
    })
  ,
  'DESCRIPTOR' : _MAPREQUEST,
  '__module__' : 'mapDemos_pb2'
  # @@protoc_insertion_point(class_scope:grpcDemo.MapRequest)
  })
_sym_db.RegisterMessage(MapRequest)
_sym_db.RegisterMessage(MapRequest.MapEntry)

MapResponse = _reflection.GeneratedProtocolMessageType('MapResponse', (_message.Message,), {
  'DESCRIPTOR' : _MAPRESPONSE,
  '__module__' : 'mapDemos_pb2'
  # @@protoc_insertion_point(class_scope:grpcDemo.MapResponse)
  })
_sym_db.RegisterMessage(MapResponse)


_MAPOBJECT_MAPOBJENTRY._options = None
_MAPREQUEST_MAPENTRY._options = None

_GREETERMAP = _descriptor.ServiceDescriptor(
  name='GreeterMap',
  full_name='grpcDemo.GreeterMap',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=289,
  serialized_end=358,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='grpcDemo.GreeterMap.SayHello',
    index=0,
    containing_service=None,
    input_type=_MAPREQUEST,
    output_type=_MAPRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETERMAP)

DESCRIPTOR.services_by_name['GreeterMap'] = _GREETERMAP

# @@protoc_insertion_point(module_scope)
