# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mapDemos_pb2 as mapDemos__pb2


class GreeterMapStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/grpcDemo.GreeterMap/SayHello',
        request_serializer=mapDemos__pb2.MapRequest.SerializeToString,
        response_deserializer=mapDemos__pb2.MapResponse.FromString,
        )


class GreeterMapServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterMapServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=mapDemos__pb2.MapRequest.FromString,
          response_serializer=mapDemos__pb2.MapResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpcDemo.GreeterMap', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
